import type { Metadata } from "next";
import { businessUnits } from "@/data/site";
import { ButtonLink, FounderVisual, SectionHeading, UnitCard } from "@/components/ui";

export const metadata: Metadata = { title: "About Ikenna Justin Ogidi & Juang Group", description: "Meet Ikenna Justin Ogidi, known as Justin Juang, and discover the African–Indonesian business story behind Juang Group." };

export default function AboutPage() {
  return <>
    <section className="page-hero section"><div className="container hero-grid"><div><p className="eyebrow">Founder &amp; Chairman</p><h1>Ikenna Justin Ogidi—The Builder Behind Juang Group.</h1><p className="lead">Widely known as Justin Juang, he is a Nigerian builder, entrepreneur, and philanthropist whose work connects African ambition with Indonesian opportunity.</p></div><FounderVisual /></div></section>
    <section className="section surface-white"><div className="container split"><div><SectionHeading eyebrow="Justin’s Story" title="From engineering roots to a cross-cultural business group." /><p>Born in 1985, Ikenna Justin Ogidi graduated from Enugu State University of Science and Technology in Nigeria. His foundation as a builder developed into a wider entrepreneurial journey spanning hospitality, lifestyle, entertainment, consumer products, trading, and investment.</p><p>As founder and chairman, Justin has guided Juang Group into a recognizable African–Indonesian lifestyle business with a growing presence across Indonesia and Africa.</p></div><div className="statement"><p>Founder’s Direction</p><blockquote>Build brands that people recognize, businesses that can grow, and opportunities that create a wider social impact.</blockquote><small>The guiding direction behind Juang Group and its expanding portfolio.</small></div></div></section>
    <section className="section dark-band"><div className="container"><SectionHeading eyebrow="The Juang Group Story" title="Built across markets, connected by ambition." light /><div className="four-grid">{["Hospitality across Indonesia and Nigeria","Lifestyle and entertainment brands","Food, beverage, coffee, and chocolate products","Investment-led expansion into new industries"].map((item, i) => <article className="dark-card" key={item}><span>0{i+1}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="The Brand Ecosystem" title="A platform designed for expansion." body="Juang Cafe, Juang Ice Cream, and Juang Books sit within a broader group vision that connects hospitality, consumer products, entertainment, trading, and investment across Indonesia and Africa." /><div className="units-grid">{businessUnits.map((unit) => <UnitCard key={unit.slug} unit={unit} />)}</div></div></section>
    <section className="section closing"><div className="container closing-inner"><h2>Discover the inclusive hospitality brand at the heart of the group.</h2><ButtonLink href="/juang-cafe" variant="light">Explore Juang Cafe</ButtonLink></div></section>
  </>;
}
