"use client";

import { cloneElement, createContext, isValidElement, useCallback, useContext, useEffect, useState, type ReactElement, type ReactNode } from "react";

export type Locale = "en" | "id";
const translations: Record<string, string> = {
  Home:"Beranda", About:"Tentang", Contact:"Kontak", Explore:"Jelajahi",
  "Skip to content":"Lewati ke konten","Open menu":"Buka menu","Close menu":"Tutup menu","Main navigation":"Navigasi utama","Mobile navigation":"Navigasi seluler",
  "Featured Concept":"Konsep Unggulan","In Development":"Dalam Pengembangan","Explore Yeshua Cafe":"Jelajahi Yeshua Cafe","View Concept":"Lihat Konsep",
  "From a vision":"Dari sebuah visi","Justin · A perspective shaped by experience":"Justin · Perspektif yang dibentuk oleh pengalaman",
  "Building commercially thoughtful businesses around culture, community, creativity, and purpose.":"Mengembangkan bisnis yang sehat dan berkelanjutan dengan berlandaskan budaya, komunitas, kreativitas, dan tujuan yang bermakna.",
  "Business enquiries":"Keperluan Bisnis","Contact details will be available soon.":"Informasi kontak resmi akan segera tersedia.","Send us a direct message and our team will respond by email.":"Kirim pesan langsung dan tim kami akan membalas melalui email.","Connect with Juang Group":"Hubungi Juang Group","Indonesia · Growing across cultures":"Indonesia · Tumbuh bersama dalam keberagaman",
  "Juang Group · Founded by Justin":"Juang Group · Didirikan oleh Justin","From a vision shaped by nearly a decade in Indonesia.":"Dari visi yang dibentuk oleh hampir satu dekade di Indonesia.","Building Businesses That Connect Culture, Community, and Purpose.":"Membangun Bisnis yang Menghubungkan Budaya, Komunitas, dan Tujuan.","Juang Group is a growing business ecosystem founded by Justin. Through thoughtful concepts in food, hospitality, lifestyle, and creativity, we aim to create businesses that are commercially sustainable and socially meaningful.":"Juang Group adalah ekosistem bisnis yang terus berkembang, didirikan oleh Justin. Melalui konsep matang di bidang kuliner, hospitalitas, gaya hidup, dan kreativitas, kami bertujuan membangun bisnis yang berkelanjutan secara komersial dan bermakna secara sosial.","Discover Our Story":"Temukan Kisah Kami",
  "years of living, learning, and building connections in Indonesia":"tahun tinggal, belajar, dan membangun hubungan di Indonesia","Meet the Founder":"Mengenal Sang Pendiri","A perspective formed across cultures.":"Sudut pandang yang tumbuh dari pengalaman lintas budaya.","Justin’s experience in Indonesia informs a practical, human-centered approach to entrepreneurship—one that sees business, creativity, and community as mutually reinforcing.":"Pengalaman Justin selama di Indonesia membentuk cara pandangnya dalam berwirausaha: praktis, dekat dengan manusia, serta menempatkan bisnis, kreativitas, dan komunitas sebagai kekuatan yang saling menguatkan.","Read Justin’s story":"Baca kisah Justin",
  "About Juang Group":"Tentang Juang Group","One Group, Multiple Possibilities.":"Satu Grup, Banyak Kemungkinan.","Meaningful connection":"Hubungan yang bermakna","Ideas shaped by local insight, experience, and shared purpose.":"Gagasan yang lahir dari pemahaman lokal, pengalaman, dan tujuan bersama.","Meaningful community":"Komunitas yang bertumbuh","Brands designed to welcome people and create opportunity.":"Membangun brand yang merangkul banyak orang sekaligus membuka peluang.","Sustainable growth":"Pertumbuhan berkelanjutan","Commercial concepts built thoughtfully for long-term relevance.":"Konsep bisnis yang dirancang dengan matang agar tetap relevan dalam jangka panjang.",
  "Our Ecosystem":"Ekosistem Kami","Distinct concepts. Shared purpose.":"Beragam konsep, satu tujuan.","Each Juang Group unit explores a different need while remaining grounded in accessible experiences, cultural curiosity, and meaningful growth.":"Setiap unit Juang Group hadir untuk menjawab kebutuhan yang berbeda, namun tetap berpijak pada pengalaman yang mudah dinikmati, keterbukaan terhadap budaya, dan pertumbuhan yang bermakna.","Vision & Values":"Visi & Nilai","How we intend to build.":"Landasan kami dalam berkarya.","Featured Business · Yeshua Cafe":"Bisnis Unggulan · Yeshua Cafe","Coffee, culture, and equal opportunity.":"Kopi, budaya, dan peluang yang setara.","Our first featured concept brings distinctive food, coffee, and a welcoming open-space environment together for students, young professionals, and communities—with an inclusive employment vision at its heart.":"Konsep unggulan pertama kami memadukan sajian khas, kopi, dan ruang terbuka yang hangat bagi mahasiswa, profesional muda, serta komunitas. Di jantungnya, ada komitmen untuk membuka kesempatan kerja yang inklusif.","Explore the Full Concept":"Lihat Konsep Selengkapnya","From a vision.":"Berawal dari visi.","Built for connection.":"Hadir untuk mendekatkan.","The next chapter":"Langkah berikutnya","Building the Next Chapter of Juang Group.":"Melangkah ke Babak Baru Juang Group.","Connect With Us":"Hubungi Kami",
  "Founder & Story":"Pendiri & Kisah","A Journey Across Cultures, Built Into a Vision.":"Perjalanan Lintas Budaya yang Menjadi Sebuah Visi.","Juang Group begins with Justin’s experience of living between contexts—and a belief that thoughtful businesses can create commercial value and meaningful connection.":"Juang Group berawal dari pengalaman Justin hidup di antara beragam konteks—serta keyakinan bahwa bisnis yang matang dapat menciptakan nilai komersial dan koneksi bermakna.","Justin’s Story":"Kisah Justin","Justin is an entrepreneur who has lived in Indonesia for approximately ten years. That time has given him a grounded understanding of Indonesian communities, local lifestyles, market opportunities, and the importance of connection and belonging.":"Justin adalah seorang pengusaha yang telah tinggal di Indonesia selama kurang lebih sepuluh tahun. Waktu tersebut memberinya pemahaman mendalam tentang komunitas Indonesia, gaya hidup lokal, peluang pasar, serta pentingnya koneksi dan rasa memiliki.","His experience shapes ideas that combine business, creativity, and community through concepts designed to feel relevant and approachable.":"Pengalamannya membentuk gagasan yang memadukan bisnis, kreativitas, dan komunitas melalui konsep yang relevan dan mudah diterima.","Founder’s Vision":"Visi Pendiri","A business can create value not only through what it sells, but also through the opportunities, relationships, and communities it helps build.":"Sebuah bisnis dapat menciptakan nilai bukan hanya melalui apa yang dijual, tetapi juga melalui peluang, relasi, dan komunitas yang turut dibangunnya.","Brand statement expressing the intended direction of Juang Group.":"Pernyataan merek yang menggambarkan arah Juang Group.","Why Juang Group":"Mengapa Juang Group","Building relevance with purpose.":"Membangun relevansi dengan tujuan.","Clear commercial potential":"Potensi komersial yang jelas","Vision-led local connection":"Koneksi lokal yang dipandu visi","Approachable, relevant experiences":"Pengalaman yang relevan dan mudah diterima","Meaningful employment and community opportunity":"Kesempatan kerja dan komunitas yang bermakna","The Ecosystem":"Ekosistem","A platform designed to grow.":"Platform yang dirancang untuk bertumbuh.","Yeshua Cafe, Juang Ice Cream, and Juang Books are the beginning of a connected ecosystem—each with its own focus and a shared commitment to culture, creativity, and sustainable growth.":"Yeshua Cafe, Juang Ice Cream, dan Juang Books adalah awal dari ekosistem yang saling terhubung—masing-masing memiliki fokus tersendiri dengan komitmen bersama terhadap budaya, kreativitas, dan pertumbuhan berkelanjutan.","See the first concept taking shape.":"Lihat konsep pertama kami mulai terwujud.",
  "A Juang Group business":"Bisnis Juang Group","The concept is being developed carefully. More information will be shared when its direction is ready.":"Konsep ini sedang dikembangkan dengan matang. Informasi lebih lanjut akan dibagikan ketika arahnya telah siap.","Back to Juang Group":"Kembali ke Juang Group","Concept in progress":"Konsep sedang dikembangkan",
  "Contact Juang Group":"Hubungi Juang Group","Start a thoughtful conversation.":"Mulai percakapan yang bermakna.","For business, strategic partnership, or investment enquiries, Juang Group welcomes aligned conversations.":"Untuk peluang bisnis, kemitraan strategis, atau investasi, Juang Group terbuka untuk percakapan yang sejalan.","Send a direct message":"Kirim pesan langsung","Your message goes directly to our team.":"Pesan Anda akan langsung diterima oleh tim kami.","Personal response":"Balasan secara personal","We will reply to the email address you provide.":"Kami akan membalas melalui alamat email yang Anda cantumkan.","Clear and confidential":"Jelas dan terjaga","Share only the information relevant to your enquiry.":"Sampaikan hanya informasi yang relevan dengan kebutuhan Anda.","Contact information":"Informasi kontak","Instant message":"Pesan langsung","Tell us what you have in mind.":"Ceritakan kebutuhan Anda.","Full name":"Nama lengkap","Your full name":"Nama lengkap Anda","Email address":"Alamat email","Subject":"Subjek","Business, partnership, or investment":"Bisnis, kemitraan, atau investasi","Message":"Pesan","Write your message here...":"Tulis pesan Anda di sini...","Please include enough detail so we can respond clearly.":"Sertakan informasi yang cukup agar kami dapat memberikan jawaban yang tepat.","Send message":"Kirim pesan","Sending message...":"Sedang mengirim...","Thank you. Your message has been saved successfully.":"Terima kasih. Pesan Anda telah tersimpan dan diterima oleh tim kami.","Your message could not be sent.":"Pesan Anda belum dapat dikirim.",
  "A new concept from Juang Group is being carefully developed. Juang Ice Cream will explore joyful flavors, cultural inspiration, and shared experiences.":"Konsep baru dari Juang Group sedang dikembangkan dengan matang. Juang Ice Cream akan mengeksplorasi rasa yang menyenangkan, inspirasi budaya, dan pengalaman bersama.","Juang Books is an upcoming Juang Group concept focused on ideas, stories, creativity, and meaningful learning experiences.":"Juang Books adalah konsep mendatang dari Juang Group yang berfokus pada gagasan, cerita, kreativitas, dan pengalaman belajar yang bermakna.",
  "Purposeful Entrepreneurship":"Kewirausahaan Bertujuan","Commercial thinking guided by a clear reason to exist.":"Pemikiran komersial yang dipandu alasan keberadaan yang jelas.","Cultural Connection":"Koneksi Budaya","Creating approachable bridges between perspectives and traditions.":"Menciptakan jembatan yang mudah didekati antara perspektif dan tradisi.","Inclusive Opportunity":"Kesempatan Inklusif","Recognizing ability, dignity, and meaningful participation.":"Mengakui kemampuan, martabat, dan partisipasi yang bermakna.","Community Growth":"Pertumbuhan Komunitas","Designing places and ideas that help relationships develop.":"Merancang tempat dan gagasan yang membantu hubungan berkembang.","Creativity":"Kreativitas","Turning cultural curiosity into relevant, distinctive experiences.":"Mengubah rasa ingin tahu budaya menjadi pengalaman yang relevan dan khas.","Sustainable Impact":"Dampak Berkelanjutan","Building responsibly with the long term in view.":"Membangun secara bertanggung jawab dengan pandangan jangka panjang.",
  "An inclusive, vision-led open-space coffee shop for students, young professionals, and communities.":"Kedai kopi ruang terbuka yang inklusif dan dipandu visi bagi mahasiswa, profesional muda, dan komunitas.","A joyful concept exploring flavor, cultural inspiration, and shared experiences.":"Konsep menyenangkan yang mengeksplorasi rasa, inspirasi budaya, dan pengalaman bersama.","An upcoming concept focused on ideas, stories, creativity, and meaningful learning.":"Konsep mendatang yang berfokus pada gagasan, cerita, kreativitas, dan pembelajaran bermakna.",
  "Juang Group presents":"Juang Group mempersembahkan","Coffee, Culture, and Equal Opportunity.":"Kopi, Budaya, dan Peluang yang Setara.","An inclusive open-space coffee shop created from a vision for students, young professionals, and communities to connect, work, study, and grow together.":"Sebuah kedai kopi inklusif dengan ruang terbuka bagi mahasiswa, profesional muda, dan komunitas untuk bertemu, bekerja, belajar, serta tumbuh bersama.","Explore the Concept":"Kenali Konsepnya","Partner With Yeshua Cafe":"Jalin Kemitraan","Community-led hospitality":"Ruang hangat yang tumbuh bersama komunitas","Follow the story":"Ikuti perjalanannya",
  "01 · The Story":"01 · Kisah","From a Vision, Built with Purpose.":"Dari Sebuah Visi, Dibangun dengan Tujuan.","After nearly a decade in Indonesia, Justin understands local communities, lifestyles, and the opportunity to create food and hospitality experiences in an approachable way.":"Setelah hampir satu dekade di Indonesia, Justin memahami komunitas lokal, gaya hidup, serta peluang untuk menciptakan pengalaman kuliner dan hospitalitas yang mudah diterima.","Yeshua Cafe is envisioned as a business where creativity, commercial potential, opportunity, and community connection can meet.":"Yeshua Cafe dibayangkan sebagai bisnis tempat kreativitas, potensi komersial, peluang, dan koneksi komunitas bertemu.",
  "02 · The Opportunity":"02 · Peluang","A familiar category with room for a stronger reason to belong.":"Pasar yang sudah dikenal, dengan peluang untuk memberi alasan yang lebih kuat bagi orang untuk datang dan merasa menjadi bagian.","Comfortable, accessible places to gather, study, work, and meet remain valuable to students and young professionals.":"Mahasiswa dan profesional muda tetap membutuhkan tempat yang nyaman dan mudah dijangkau untuk berkumpul, belajar, bekerja, maupun bertemu.","Many cafes compete on interior and beverages without a distinctive cultural or social identity.":"Banyak kafe mengandalkan interior dan minuman, tetapi belum memiliki identitas sosial atau budaya yang benar-benar membedakan.","Distinctive food concepts can create room for approachable discovery in a competitive cafe market.":"Di tengah pasar kafe yang kompetitif, sajian khas dapat menghadirkan pengalaman baru yang tetap akrab dan mudah dinikmati.","People with Down syndrome often face limited access to structured, supportive employment opportunities.":"Penyandang Down syndrome masih memiliki akses yang terbatas terhadap kesempatan kerja yang terstruktur, aman, dan didukung dengan baik.",
  "03 · The Solution":"03 · Solusi","A cafe designed as useful social infrastructure.":"Kafe yang dirancang sebagai infrastruktur sosial yang bermanfaat.","Open-space coffee shop":"Kedai kopi ruang terbuka","Comfortable study and work seating":"Tempat duduk nyaman untuk belajar dan bekerja","Wi-Fi and charging access":"Akses Wi-Fi dan pengisian daya","Community tables":"Meja komunitas","Coffee and beverages":"Kopi dan minuman","Vision-led food concept":"Konsep makanan berbasis visi","Ice cream and desserts":"Es krim dan hidangan penutup","Inclusive employment program":"Program ketenagakerjaan inklusif","Community events":"Acara komunitas","Cultural experiences":"Pengalaman budaya",
  "04 · The Experience":"04 · Pengalaman","Designed to Relax, Work, and Connect.":"Nyaman untuk Bersantai, Mendukung untuk Berkarya.","One space, many ways to belong.":"Satu ruang untuk beragam kebutuhan.","Relax · Work · Study · Connect":"Bersantai · Bekerja · Belajar · Terhubung","Open and welcoming layout":"Tata ruang terbuka dan bersahabat","Study-friendly seating":"Tempat duduk yang nyaman untuk belajar","Work-friendly tables":"Meja yang mendukung produktivitas","Free Wi-Fi":"Wi-Fi gratis","Accessible charging points":"Akses stopkontak yang mudah","Community area":"Area untuk komunitas","Semi-outdoor atmosphere":"Suasana semi-terbuka","Relaxed music":"Musik dengan suasana santai","Warm hospitality":"Pelayanan yang hangat","Photogenic, functional interior":"Interior menarik sekaligus fungsional",
  "05 · Menu Concept":"05 · Konsep Menu","From a Vision, Made for Connection.":"Berawal dari Visi, Hadir untuk Dinikmati Bersama.","The menu will be developed with a distinctive character while remaining approachable and relevant for Indonesian consumers. No prices or unconfirmed recipe claims are presented at this stage.":"Menu Yeshua Cafe akan dikembangkan dengan karakter yang khas, namun tetap akrab dan sesuai dengan selera konsumen Indonesia. Pada tahap ini, harga dan detail resep belum ditetapkan.","From a vision, served with character.":"Berawal dari visi, hadir dengan karakter.","Signature Food · Coffee & Beverages · Dessert & Ice Cream":"Sajian Khas · Kopi & Minuman · Hidangan Penutup & Es Krim","Featured Menu":"Menu Pilihan","Eight dishes, one welcoming table.":"Delapan sajian untuk dinikmati bersama.","African Meat Pie":"Pai Daging Afrika","Shawarmas":"Shawarma","African Coconut Rice":"Nasi Kelapa Afrika","African Jollof Rice":"Nasi Jollof Afrika","African Fried Rice":"Nasi Goreng Afrika","Burger":"Burger","Martabak":"Martabak","Spaghetti":"Spageti","Signature Beverages":"Minuman Andalan","Six refreshing signatures, styled to stand out.":"Enam minuman segar dengan karakter yang khas.","Blue Ocean":"Blue Ocean","Lemon water, soda, blue lagoon syrup, basil seeds, and mint leaves.":"Air lemon, soda, sirup blue lagoon, biji selasih, dan daun mint.","Strawberry Squash Mocha":"Strawberry Squash Mocha","Strawberry, syrup, sugar-free soda water, and edible glitter.":"Stroberi, sirup, air soda tanpa gula, dan glitter yang aman dikonsumsi.","Yakult":"Yakult","Yakult, water, mocha syrup, and lime squash.":"Yakult, air, sirup mocha, dan lime squash.","Watermelon Juice":"Jus Semangka","Real orange blended with fresh watermelon juice.":"Jeruk asli yang dipadukan dengan jus semangka segar.","Taro Mocha":"Taro Mocha","Mocha powder, creamy taro milk, fresh milk, and taro powder.":"Bubuk mocha, susu taro yang creamy, susu segar, dan bubuk taro.","Coffee Butterscotch":"Kopi Butterscotch","Butterscotch cream powder, butterscotch syrup, fresh milk, and espresso.":"Bubuk krim butterscotch, sirup butterscotch, susu segar, dan espresso.","Signature Food":"Sajian Khas","Signature rice dishes":"Aneka nasi andalan","House-made savory pies":"Pai gurih buatan dapur kami","Distinctive snacks":"Pilihan kudapan khas","Rotating seasonal dishes":"Menu musiman yang berganti secara berkala","Coffee & Beverages":"Kopi & Minuman","Espresso-based coffee":"Pilihan kopi berbasis espresso","Iced coffee":"Kopi dingin","Manual brew":"Kopi seduh manual","Signature and non-coffee beverages":"Minuman khas dan pilihan non-kopi","Dessert & Ice Cream":"Hidangan Penutup & Es Krim","Ice cream":"Es krim","Pastries":"Aneka pastri","Light desserts":"Hidangan penutup ringan","Future Juang Ice Cream collaboration":"Rencana kolaborasi dengan Juang Ice Cream",
  "06 · Inclusive Employment":"06 · Ketenagakerjaan Inklusif","Equal Opportunity, Meaningful Work.":"Kesempatan Setara, Pekerjaan Bermakna.","Yeshua Cafe aims to provide structured, supportive, and meaningful employment opportunities for individuals with Down syndrome based on each person’s abilities, strengths, readiness, and development needs.":"Yeshua Cafe bertujuan menyediakan kesempatan kerja yang terstruktur, suportif, dan bermakna bagi penyandang Down syndrome berdasarkan kemampuan, kekuatan, kesiapan, serta kebutuhan pengembangan masing-masing.","Potential roles may include greeting, light table service, preparation, packaging, cleaning support, and selected operational tasks. Implementation should involve clear SOPs, training, safe supervision, fair treatment, and coordination with families, communities, foundations, or professional companions.":"Peran potensial dapat mencakup menyambut tamu, layanan meja ringan, persiapan, pengemasan, dukungan kebersihan, dan tugas operasional tertentu. Pelaksanaannya perlu melibatkan SOP yang jelas, pelatihan, pengawasan yang aman, perlakuan adil, serta koordinasi dengan keluarga, komunitas, yayasan, atau pendamping profesional.","Inclusion is an operating commitment—not a marketing gimmick.":"Inklusi adalah komitmen operasional—bukan sekadar gimmick pemasaran.","Ability in action.":"Kemampuan dalam aksi.","Structured support, meaningful roles, dignity, and room to grow.":"Dukungan terstruktur, peran bermakna, martabat, dan ruang untuk bertumbuh.",
  "07 · Target Market":"07 · Target Pasar","Three communities, one welcoming space.":"Tiga kelompok, satu ruang yang terasa akrab.","Different needs. Shared belonging.":"Kebutuhan berbeda, rasa memiliki yang sama.","Students · Professionals · Communities":"Mahasiswa · Profesional · Komunitas","University Students":"Mahasiswa","Study space":"Tempat belajar","Affordable meals":"Pilihan makanan yang terjangkau","Group assignments":"Tempat mengerjakan tugas bersama","Campus community events":"Kegiatan komunitas kampus","Young Professionals":"Profesional Muda","Remote work":"Bekerja jarak jauh","Informal meetings":"Pertemuan santai","After-office gathering":"Berkumpul selepas kerja","Comfortable workspace":"Ruang kerja yang nyaman","Communities":"Komunitas","Small events":"Acara berskala kecil","Cultural gatherings":"Kegiatan budaya","Workshops":"Lokakarya","Open mic and creative activities":"Open mic dan kegiatan kreatif",
  "08 · Business Model":"08 · Model Bisnis","Built around daily trade, designed for optionality.":"Bertumpu pada penjualan harian, terbuka untuk berbagai peluang.","Core Revenue":"Sumber Pendapatan Utama","Food, coffee, beverages, ice cream, and desserts.":"Makanan, kopi, aneka minuman, es krim, dan hidangan penutup.","Future Opportunities":"Peluang Pengembangan","Meeting packages, reservations, catering, private events, merchandise, packaged products, and potential partnerships.":"Paket pertemuan, reservasi, katering, acara privat, merchandise, produk kemasan, serta berbagai peluang kemitraan.",
  "09 · Connected Operations":"09 · Operasional Terintegrasi","From Table to Dashboard, Every Step Connected.":"Dari Meja hingga Dashboard, Semua Saling Terhubung.","Yeshua Cafe plans to use an integrated digital workflow that connects table ordering, cashier records, kitchen preparation, inventory movement, and management reporting in one traceable system.":"Yeshua Cafe merencanakan alur kerja digital yang menghubungkan pemesanan di meja, pencatatan kasir, proses di dapur, pergerakan stok, hingga laporan manajemen dalam satu sistem yang transparan dan mudah ditelusuri.","One order. One connected flow.":"Satu pesanan, satu alur yang terhubung.","QR Order · Cashier · Kitchen · Inventory · Dashboard":"Pesan via QR · Kasir · Dapur · Gudang · Dashboard","Simpler Ordering":"Pemesanan Lebih Praktis","Guests scan a QR code at the table and send orders directly, helping reduce queues and unnecessary waiting.":"Pengunjung cukup memindai QR di meja untuk mengirim pesanan secara langsung, sehingga antrean dan waktu tunggu dapat dikurangi.","More Accurate Execution":"Proses Lebih Akurat","A shared order record across cashier and kitchen helps minimize repeated entry and avoid preventable order mistakes.":"Data pesanan yang sama diteruskan ke kasir dan dapur, sehingga input berulang dan kesalahan pencatatan dapat diminimalkan.","Traceable Inventory":"Stok Mudah Ditelusuri","Ingredient usage, stock changes, and asset movement can be recorded against daily operating activity.":"Pemakaian bahan, perubahan stok, dan pergerakan aset dapat tercatat bersama aktivitas operasional harian.","Clearer Investor Visibility":"Visibilitas bagi Investor","Authorized reporting gives investors a clearer view of sales, stock, and asset movement without disrupting operations.":"Melalui laporan dengan akses terkontrol, investor dapat memantau penjualan, stok, dan pergerakan aset tanpa mengganggu kegiatan operasional.","The final technology stack, access controls, integrations, and reporting scope will be validated during implementation.":"Pilihan teknologi, pengaturan akses, integrasi, dan cakupan laporan akan divalidasi lebih lanjut pada tahap implementasi.",
  "10 · Go-to-Market":"10 · Strategi Memasuki Pasar","11 · Competitive Advantage":"11 · Keunggulan Kompetitif","12 · Future Impact Measurement":"12 · Rencana Pengukuran Dampak","13 · Roadmap":"13 · Peta Jalan","14 · Investment Opportunity":"14 · Peluang Investasi",
  "09 · Go-to-Market":"09 · Strategi Memasuki Pasar","Community before campaign.":"Bangun komunitas sebelum menjalankan kampanye.","Build relationships before reach.":"Dahulukan relasi, lalu perluas jangkauan.","Digital · Campus · Community · Partnership":"Digital · Kampus · Komunitas · Kemitraan","Digital":"Digital","Campus":"Kampus","Community":"Komunitas","Partnership":"Kemitraan",
  "10 · Competitive Advantage":"10 · Keunggulan Kompetitif","Why Yeshua Cafe Can Stand Out.":"Alasan Yeshua Cafe Memiliki Daya Pembeda.","11 · Future Impact Measurement":"11 · Rencana Pengukuran Dampak","Measure progress, never manufacture it.":"Mengukur kemajuan secara jujur dan bertanggung jawab.","These are proposed indicators for the future—not current results.":"Indikator berikut merupakan rencana pengukuran ke depan, bukan hasil yang telah dicapai saat ini.","12 · Roadmap":"12 · Peta Jalan","A disciplined path from validation to growth.":"Langkah terarah, dari validasi hingga pertumbuhan.","Phase 1":"Fase 1","Phase 2":"Fase 2","Phase 3":"Fase 3","Phase 4":"Fase 4","Validation & Preparation":"Validasi & Persiapan","Development":"Pengembangan","Launch":"Peluncuran","Growth":"Pertumbuhan",
  "13 · Investment Opportunity":"13 · Peluang Investasi","Building a Sustainable and Inclusive Business Together.":"Bersama Membangun Bisnis yang Inklusif dan Berkelanjutan.","To Be Finalized":"Dalam Tahap Finalisasi","Let’s build together":"Mari bertumbuh bersama","Let’s Build a Cafe Where Everyone Has a Place.":"Mari Hadirkan Kafe Tempat Setiap Orang Punya Ruang.","Connect With Juang Group":"Hubungi Juang Group","Return to Juang Group":"Kembali ke Juang Group","Discuss the Investment":"Diskusikan Peluang Investasi",
  "Instagram, TikTok, Google Business Profile, creators, UGC, founder storytelling":"Instagram, TikTok, Google Business Profile, kreator, UGC, dan kisah pendiri","Potential ambassadors, study packages, student offers, partnerships, sponsorship":"Calon duta, paket belajar, penawaran mahasiswa, kemitraan, dan sponsor","Cultural nights, open mic, workshops, inclusive programs, exhibitions":"Malam budaya, open mic, lokakarya, program inklusif, dan pameran","Proposed collaboration with universities, companies, foundations, communities, and cultural organizations":"Usulan kolaborasi dengan universitas, perusahaan, yayasan, komunitas, dan organisasi budaya",
  "Distinctive vision-led menu":"Menu khas berbasis visi","Strong founder story":"Kisah pendiri yang kuat","Inclusive social purpose":"Tujuan sosial yang inklusif","Youth-oriented open-space concept":"Konsep ruang terbuka berorientasi anak muda","Community-based brand":"Merek berbasis komunitas","Multiple revenue possibilities":"Beragam potensi pendapatan","Connection with future Juang Group brands":"Keterhubungan dengan merek Juang Group mendatang",
  "Inclusive employees trained and hired":"Karyawan inklusif yang dilatih dan direkrut","Training hours and development progress":"Jam pelatihan dan kemajuan pengembangan","Community partnerships and events":"Kemitraan dan acara komunitas","Employee retention":"Retensi karyawan","Customer awareness of inclusive employment":"Kesadaran pelanggan terhadap ketenagakerjaan inklusif",
  "Concept, location, research, menu, planning, branding, licensing preparation":"Konsep, lokasi, riset, menu, perencanaan, branding, dan persiapan perizinan","Renovation, equipment, recruitment, training, SOPs, suppliers, pre-launch":"Renovasi, peralatan, rekrutmen, pelatihan, SOP, pemasok, dan prapeluncuran","Soft opening, community and creator invitations, campaign, feedback, evaluation":"Soft opening, undangan komunitas dan kreator, kampanye, masukan, dan evaluasi","Catering, events, CSR partnerships, packaged products, location feasibility":"Katering, acara, kemitraan CSR, produk kemasan, dan kelayakan lokasi",
  "Yeshua Cafe is preparing a concept that can be developed with aligned investors and strategic partners. Potential use of funds includes location, renovation, equipment, furniture, initial inventory, licensing, recruitment, training, marketing, and working capital.":"Yeshua Cafe sedang menyiapkan konsep yang dapat dikembangkan bersama investor dan mitra strategis yang sejalan. Potensi penggunaan dana mencakup lokasi, renovasi, peralatan, furnitur, persediaan awal, perizinan, rekrutmen, pelatihan, pemasaran, dan modal kerja.","Funding Requirement":"Kebutuhan Pendanaan","Proposed Business Structure":"Usulan Struktur Bisnis","Revenue Projection":"Proyeksi Pendapatan","Break-Even Projection":"Proyeksi Titik Impas","Opening Target":"Target Pembukaan","Investor Return Structure":"Struktur Imbal Hasil Investor",
  "Founder & Chairman":"Pendiri & Chairman","Ikenna Justin Ogidi · Known as Justin Juang":"Ikenna Justin Ogidi · Dikenal sebagai Justin Juang",
  "Juang Group · Indonesia & Africa":"Juang Group · Indonesia & Afrika","Founded and chaired by Ikenna Justin Ogidi—widely known as Justin Juang.":"Didirikan dan dipimpin oleh Ikenna Justin Ogidi—yang dikenal luas sebagai Justin Juang.","A Lifestyle and Entertainment Group Built Across Cultures.":"Grup Lifestyle dan Entertainment yang Tumbuh Lintas Budaya.","Juang Group is an African–Indonesian lifestyle and entertainment group with businesses spanning hospitality, dining, consumer products, trading, and investment. From Indonesia to Africa, the group continues to expand through brands designed for quality, relevance, and lasting impact.":"Juang Group adalah grup lifestyle dan entertainment Afrika–Indonesia dengan bisnis yang mencakup hospitality, kuliner, produk konsumen, perdagangan, dan investasi. Dari Indonesia hingga Afrika, grup ini terus memperluas jangkauan melalui brand yang mengutamakan kualitas, relevansi, dan dampak jangka panjang.",
  "the birth year of founder and chairman Ikenna Justin Ogidi":"tahun kelahiran pendiri dan chairman Ikenna Justin Ogidi","The builder behind Juang Group.":"Sosok builder di balik Juang Group.","A Nigerian builder, entrepreneur, and philanthropist, Justin graduated from Enugu State University of Science and Technology. His experience across Nigeria and Indonesia has shaped Juang Group into a recognizable cross-cultural lifestyle business.":"Justin adalah builder, pengusaha, dan filantropis asal Nigeria yang lulus dari Enugu State University of Science and Technology. Pengalamannya di Nigeria dan Indonesia membentuk Juang Group menjadi bisnis lifestyle lintas budaya yang semakin dikenal.",
  "Core Divisions":"Lini Bisnis Utama","A diversified group with a lifestyle focus.":"Grup usaha yang beragam dengan lifestyle sebagai kekuatan utama.","Hospitality & Dining":"Hospitality & Kuliner","Cafes, restaurants, and entertainment-led hospitality brands across Indonesia and Nigeria, including Jakarta.":"Jaringan kafe, restoran, dan brand hospitality berbasis entertainment di Indonesia dan Nigeria, termasuk Jakarta.","Consumer Products":"Produk Konsumen","Food and beverage brands including Jinggle Bells Ice Creams, coffee, and chocolate products.":"Portofolio makanan dan minuman, termasuk Jinggle Bells Ice Creams, produk kopi, dan cokelat.","Trading & Investment":"Perdagangan & Investasi","A commercial platform supporting product development, distribution, partnerships, and expansion into new industries.":"Platform bisnis yang mendukung pengembangan produk, distribusi, kemitraan, dan ekspansi ke berbagai industri baru.",
  "Our Brand Ecosystem":"Ekosistem Brand Kami","From hospitality to consumer brands.":"Dari hospitality hingga produk konsumen.","Juang Group brings together complementary businesses with room to grow across Indonesia, Nigeria, and wider African markets.":"Juang Group menyatukan berbagai bisnis yang saling melengkapi dengan peluang pertumbuhan di Indonesia, Nigeria, dan pasar Afrika yang lebih luas.","How Juang Group continues to grow.":"Landasan pertumbuhan Juang Group.","A cafe brand built around inclusion.":"Brand kafe yang tumbuh bersama nilai inklusi.","Founded by Justin, Yeshua Cafe is growing across Jakarta and Indonesia with a defining mission: to create welcoming hospitality experiences while opening meaningful employment opportunities for people with Down syndrome.":"Didirikan oleh Justin, Yeshua Cafe terus berkembang di Jakarta dan berbagai wilayah Indonesia dengan satu misi utama: menghadirkan pengalaman hospitality yang hangat sekaligus membuka kesempatan kerja yang bermakna bagi penyandang Down syndrome.","Inclusive by purpose.":"Inklusif sejak awal.","Growing with people.":"Bertumbuh bersama manusia.","Growing across industries":"Tumbuh lintas industri","Building Recognizable Brands Across Indonesia and Africa.":"Membangun Brand yang Dikenal di Indonesia dan Afrika.",
  "Ikenna Justin Ogidi—The Builder Behind Juang Group.":"Ikenna Justin Ogidi—Sosok Builder di Balik Juang Group.","Widely known as Justin Juang, he is a Nigerian builder, entrepreneur, and philanthropist whose work connects African ambition with Indonesian opportunity.":"Dikenal luas sebagai Justin Juang, ia adalah builder, pengusaha, dan filantropis asal Nigeria yang menghubungkan semangat Afrika dengan peluang di Indonesia.","From engineering roots to a cross-cultural business group.":"Dari latar belakang teknik menuju grup bisnis lintas budaya.","Born in 1985, Ikenna Justin Ogidi graduated from Enugu State University of Science and Technology in Nigeria. His foundation as a builder developed into a wider entrepreneurial journey spanning hospitality, lifestyle, entertainment, consumer products, trading, and investment.":"Lahir pada 1985, Ikenna Justin Ogidi menyelesaikan pendidikan di Enugu State University of Science and Technology, Nigeria. Latar belakangnya sebagai builder kemudian berkembang menjadi perjalanan bisnis yang mencakup hospitality, lifestyle, entertainment, produk konsumen, perdagangan, dan investasi.","As founder and chairman, Justin has guided Juang Group into a recognizable African–Indonesian lifestyle business with a growing presence across Indonesia and Africa.":"Sebagai pendiri dan chairman, Justin membawa Juang Group menjadi bisnis lifestyle Afrika–Indonesia yang semakin dikenal dan terus memperluas kehadirannya di Indonesia serta Afrika.",
  "Founder’s Direction":"Arah Sang Pendiri","Build brands that people recognize, businesses that can grow, and opportunities that create a wider social impact.":"Membangun brand yang dikenal, bisnis yang mampu bertumbuh, serta peluang yang menghadirkan dampak sosial lebih luas.","The guiding direction behind Juang Group and its expanding portfolio.":"Prinsip yang mengarahkan Juang Group dan perkembangan portofolio bisnisnya.","The Juang Group Story":"Perjalanan Juang Group","Built across markets, connected by ambition.":"Tumbuh di berbagai pasar, disatukan oleh ambisi.","Hospitality across Indonesia and Nigeria":"Hospitality di Indonesia dan Nigeria","Lifestyle and entertainment brands":"Brand lifestyle dan entertainment","Food, beverage, coffee, and chocolate products":"Produk makanan, minuman, kopi, dan cokelat","Investment-led expansion into new industries":"Ekspansi ke industri baru melalui investasi","The Brand Ecosystem":"Ekosistem Brand","A platform designed for expansion.":"Platform yang dirancang untuk ekspansi.","Yeshua Cafe, Juang Ice Cream, and Juang Books sit within a broader group vision that connects hospitality, consumer products, entertainment, trading, and investment across Indonesia and Africa.":"Yeshua Cafe, Juang Ice Cream, dan Juang Books berada dalam visi grup yang lebih luas, menghubungkan hospitality, produk konsumen, entertainment, perdagangan, dan investasi di Indonesia serta Afrika.","Discover the inclusive hospitality brand at the heart of the group.":"Kenali brand hospitality inklusif yang menjadi bagian penting dari grup.",
  "Entrepreneurial Ambition":"Ambisi Wirausaha","Building recognizable brands with the discipline and confidence to expand.":"Membangun brand yang dikenal dengan disiplin dan keberanian untuk berekspansi.","African–Indonesian Connection":"Koneksi Afrika–Indonesia","Creating commercial bridges between markets, cultures, and opportunities.":"Membuka jembatan bisnis antara pasar, budaya, dan peluang.","Hospitality Excellence":"Keunggulan Hospitality","Creating welcoming experiences with quality, relevance, and strong execution.":"Menghadirkan pengalaman yang hangat dengan kualitas, relevansi, dan eksekusi yang kuat.","Portfolio Growth":"Pertumbuhan Portofolio","Expanding from hospitality into consumer products, trading, investment, and new industries.":"Berkembang dari hospitality menuju produk konsumen, perdagangan, investasi, dan industri baru.","Lasting Impact":"Dampak Berkelanjutan","Growing responsibly while creating value for customers, communities, partners, and investors.":"Bertumbuh secara bertanggung jawab sambil menciptakan nilai bagi pelanggan, komunitas, mitra, dan investor.",
  "Justin Juang’s inclusive hospitality brand, growing across Jakarta and Indonesia while creating meaningful roles for people with Down syndrome.":"Brand hospitality inklusif milik Justin Juang yang terus berkembang di Jakarta dan Indonesia sambil membuka peran bermakna bagi penyandang Down syndrome.","Part of the group’s growing food and beverage portfolio, inspired by joyful flavors and shared experiences.":"Bagian dari portofolio makanan dan minuman grup yang terus berkembang, terinspirasi oleh rasa yang menyenangkan dan pengalaman bersama.","A future lifestyle concept focused on ideas, stories, creativity, and meaningful learning.":"Konsep lifestyle masa depan yang berfokus pada gagasan, cerita, kreativitas, dan pembelajaran bermakna.",
  "Founded by Justin Juang":"Didirikan oleh Justin Juang","Inclusive Hospitality, Built to Grow.":"Hospitality Inklusif yang Dibangun untuk Bertumbuh.","An inspiring cafe brand growing across Jakarta and Indonesia, bringing people together while creating meaningful employment opportunities for people with Down syndrome.":"Brand kafe inspiratif yang berkembang di Jakarta dan berbagai wilayah Indonesia, mempertemukan banyak orang sekaligus membuka kesempatan kerja yang bermakna bagi penyandang Down syndrome.","Discover Yeshua Cafe":"Kenali Yeshua Cafe","Hospitality with purpose":"Hospitality yang punya tujuan","Founded by Justin. Driven by Inclusion.":"Didirikan oleh Justin. Digerakkan oleh Inklusi.","Yeshua Cafe was founded by Ikenna Justin Ogidi, widely known as Justin Juang, as a hospitality brand with a clear social purpose.":"Yeshua Cafe didirikan oleh Ikenna Justin Ogidi, yang dikenal luas sebagai Justin Juang, sebagai brand hospitality dengan tujuan sosial yang jelas.","From its presence around Jakarta, the brand is expanding across Indonesia with the ambition to create welcoming cafe experiences and open more supported employment opportunities for people with Down syndrome.":"Berawal dari kehadirannya di sekitar Jakarta, Yeshua Cafe terus berkembang ke berbagai wilayah Indonesia dengan semangat menghadirkan pengalaman kafe yang hangat dan membuka lebih banyak kesempatan kerja yang didukung dengan baik bagi penyandang Down syndrome.",
  "The Yeshua Cafe menu brings together distinctive character and approachable choices for Indonesian consumers, spanning signature food, coffee, beverages, desserts, and ice cream.":"Menu Yeshua Cafe memadukan karakter yang khas dengan pilihan yang akrab bagi konsumen Indonesia, mulai dari sajian andalan, kopi, aneka minuman, hidangan penutup, hingga es krim.","Inclusive employment is central to Yeshua Cafe’s identity. The brand is committed to creating structured, supportive, and meaningful roles for people with Down syndrome based on each person’s abilities, strengths, readiness, and development needs.":"Ketenagakerjaan inklusif adalah bagian utama dari identitas Yeshua Cafe. Brand ini berkomitmen menciptakan peran yang terstruktur, suportif, dan bermakna bagi penyandang Down syndrome sesuai kemampuan, kekuatan, kesiapan, serta kebutuhan pengembangan setiap individu.","Expanding a Sustainable and Inclusive Brand Together.":"Bersama Memperluas Brand yang Inklusif dan Berkelanjutan.","Yeshua Cafe welcomes aligned investors and strategic partners to support responsible expansion across Indonesia. Potential use of funds includes new locations, renovation, equipment, furniture, inventory, licensing, recruitment, inclusive training, technology, marketing, and working capital.":"Yeshua Cafe membuka peluang bagi investor dan mitra strategis yang sejalan untuk mendukung ekspansi yang bertanggung jawab di Indonesia. Potensi penggunaan dana mencakup lokasi baru, renovasi, peralatan, furnitur, persediaan, perizinan, rekrutmen, pelatihan inklusif, teknologi, pemasaran, dan modal kerja.",
  "Foundation & Systems":"Fondasi & Sistem","Strengthen brand standards, SOPs, inclusive training, technology, menu consistency, and operating controls":"Memperkuat standar brand, SOP, pelatihan inklusif, teknologi, konsistensi menu, dan pengendalian operasional","Jakarta Network":"Jaringan Jakarta","Grow the cafe presence around Jakarta through disciplined locations, partnerships, and community engagement":"Memperluas kehadiran kafe di Jakarta melalui pemilihan lokasi yang disiplin, kemitraan, dan keterlibatan komunitas","Indonesia Expansion":"Ekspansi Indonesia","Expand into selected Indonesian cities while developing local teams and supported inclusive employment":"Berekspansi ke kota-kota terpilih di Indonesia sambil mengembangkan tim lokal dan ketenagakerjaan inklusif yang didukung dengan baik","Long-Term Growth":"Pertumbuhan Jangka Panjang","Build catering, events, packaged products, strategic partnerships, and wider Juang Group collaboration":"Mengembangkan katering, acara, produk kemasan, kemitraan strategis, dan kolaborasi yang lebih luas di dalam Juang Group",
};

const originalText = new WeakMap<Text, string>();

const Context = createContext<{ locale: Locale; t: (text: string) => string; setLocale: (locale: Locale) => void }>({ locale:"en", t:(s)=>s, setLocale:()=>undefined });
export function LanguageProvider({children}:{children:React.ReactNode}) {
  const [locale,setState]=useState<Locale>("en");
  useEffect(()=>{
    const saved: Locale=localStorage.getItem("juang-language")==="id"?"id":"en";
    document.documentElement.lang=saved;
    const frame=requestAnimationFrame(()=>setState(saved));
    return ()=>cancelAnimationFrame(frame);
  },[]);
  const setLocale=useCallback((next:Locale)=>{setState(next);localStorage.setItem("juang-language",next);document.documentElement.lang=next},[]);
  const t=useCallback((text:string)=>locale==="id"?(translations[text]??text):text,[locale]);
  useEffect(()=>{
    const translatePage=()=>{
      const root=document.querySelector("main");
      if (!root) return;
      const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
      let current=walker.nextNode();
      while (current) {
        const textNode=current as Text;
        if (!originalText.has(textNode)) originalText.set(textNode,textNode.data);
        const source=originalText.get(textNode) ?? textNode.data;
        const trimmed=source.trim();
        const translated=locale==="id" ? translations[trimmed] : undefined;
        if (locale==="en") {
          textNode.data=source;
        } else if (translated) {
          const start=source.slice(0,source.indexOf(trimmed));
          const end=source.slice(source.indexOf(trimmed)+trimmed.length);
          textNode.data=`${start}${translated}${end}`;
        }
        current=walker.nextNode();
      }
    };
    translatePage();
    const root=document.querySelector("main");
    if (!root) return;
    const observer=new MutationObserver(()=>translatePage());
    observer.observe(root,{childList:true,subtree:true});
    return ()=>observer.disconnect();
  },[locale]);
  return <Context.Provider value={{locale,t,setLocale}}>{children}</Context.Provider>;
}
export const useLanguage=()=>useContext(Context);

function translateNode(node: ReactNode, t: (text: string) => string): ReactNode {
  if (typeof node === "string") return t(node);
  if (Array.isArray(node)) return node.map((child) => translateNode(child, t));
  if (isValidElement(node) && node.props && typeof node.props === "object" && "children" in node.props) {
    const element = node as ReactElement<{ children?: ReactNode }>;
    return cloneElement(element, {}, translateNode(element.props.children, t));
  }
  return node;
}

export function LocalizedContent({ children }: { children: ReactNode }) {
  const { t } = useLanguage();
  return <>{translateNode(children, t)}</>;
}
