import type { Metadata } from "next";
import Image from "next/image";
import { Check, CircleArrowDown, ClipboardCheck, HandHeart, HardHat, Lightbulb, PackageCheck, PartyPopper, QrCode, ReceiptText, TrendingUp, Users, View } from "lucide-react";
import { ButtonLink, SectionHeading } from "@/components/ui";
import { beverageMenu, experience, featuredMenu, menuGroups, opportunity, roadmap, targetMarkets } from "@/data/cafe";

export const metadata: Metadata = { title: "Juang Cafe | Inclusive Hospitality by Juang Group", description: "Discover Justin Juang’s inclusive cafe brand, growing across Jakarta and Indonesia while creating meaningful employment opportunities for people with Down syndrome." };
const solution = ["Open-space coffee shop","Comfortable study and work seating","Wi-Fi and charging access","Community tables","Coffee and beverages","Vision-led food concept","Ice cream and desserts","Inclusive employment program","Community events","Cultural experiences"];
const advantages = ["Distinctive vision-led menu","Strong founder story","Inclusive social purpose","Youth-oriented open-space concept","Community-based brand","Multiple revenue possibilities","Connection with future Juang Group brands"];
const roadmapIcons = [ClipboardCheck, HardHat, PartyPopper, TrendingUp];

export default function CafePage() {
  return <>
    <section className="cafe-hero section"><div className="container cafe-hero-inner"><div><p className="eyebrow">Founded by Justin Juang</p><h1><span>Juang Cafe</span>Inclusive Hospitality, Built to Grow.</h1><p className="lead">An inspiring cafe brand growing across Jakarta and Indonesia, bringing people together while creating meaningful employment opportunities for people with Down syndrome.</p><div className="actions"><ButtonLink href="#concept">Discover Juang Cafe</ButtonLink><ButtonLink href="#investment" variant="outline">Partner With Juang Cafe</ButtonLink></div></div><figure className="cafe-hero-image"><Image src="/images/juang-cafe/community-cafe.webp" alt="Editorial illustration of Juang Cafe as a welcoming and inclusive hospitality brand" fill priority sizes="(max-width: 900px) 100vw, 46vw" /><figcaption><span>Hospitality with purpose</span><strong>JC</strong></figcaption></figure></div><a className="scroll-cue" href="#story">Follow the story <CircleArrowDown aria-hidden /></a></section>
    <section id="story" className="section surface-white"><div className="container split"><SectionHeading eyebrow="01 · The Story" title="Founded by Justin. Driven by Inclusion." /><div><p className="lead">Juang Cafe was founded by Ikenna Justin Ogidi, widely known as Justin Juang, as a hospitality brand with a clear social purpose.</p><p>From its presence around Jakarta, the brand is expanding across Indonesia with the ambition to create welcoming cafe experiences and open more supported employment opportunities for people with Down syndrome.</p></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="02 · The Opportunity" title="A familiar category with room for a stronger reason to belong." /><div className="two-grid">{opportunity.map((item, i) => <article className="number-card" key={item}><span>0{i+1}</span><p>{item}</p></article>)}</div></div></section>
    <section id="concept" className="section dark-band"><div className="container"><SectionHeading eyebrow="03 · The Solution" title="A cafe designed as useful social infrastructure." light /><div className="check-grid">{solution.map((item) => <div key={item}><Check aria-hidden /><span>{item}</span></div>)}</div></div></section>
    <section id="cafe-experience" className="section surface-ceramic"><div className="container"><SectionHeading eyebrow="04 · The Experience" title="Designed to Relax, Work, and Connect." /><figure className="experience-illustration"><Image src="/images/juang-cafe/cafe-experience.webp" alt="Panoramic illustration of Juang Cafe with spaces to relax, study, work, and connect in a leafy semi-outdoor setting" fill sizes="(max-width: 900px) 100vw, 1180px" /><figcaption><strong>One space, many ways to belong.</strong><span>Relax · Work · Study · Connect</span></figcaption></figure><div className="experience-grid">{experience.map((item, i) => <article key={item}><span>{String(i+1).padStart(2,"0")}</span><h3>{item}</h3></article>)}</div></div></section>
    <section id="menu-concept" className="section surface-white"><div className="container"><SectionHeading eyebrow="05 · Menu Concept" title="From a Vision, Made for Connection." body="The Juang Cafe menu brings together distinctive character and approachable choices for Indonesian consumers, spanning signature food, coffee, beverages, desserts, and ice cream." /><figure className="menu-illustration"><Image src="/images/juang-cafe/menu-concept-real-menu.webp" alt="A Juang Cafe table spread featuring signature rice dishes, meat pies, shawarmas, burger, martabak, spaghetti, and signature beverages" fill sizes="(max-width: 900px) 100vw, 1180px" /><figcaption><strong>From a vision, served with character.</strong><span>Signature Food · Coffee &amp; Beverages · Dessert &amp; Ice Cream</span></figcaption></figure><div className="featured-menu-heading"><p className="eyebrow">Featured Menu</p><h3>Eight dishes, one welcoming table.</h3></div><div className="featured-menu-grid">{featuredMenu.map((item, index) => <article className="featured-menu-card" key={item.name}><div className="featured-menu-photo"><Image src={item.image} alt={`${item.name} from the Juang Cafe menu`} fill sizes="(max-width: 600px) 100vw, (max-width: 900px) 50vw, 25vw" style={{ objectPosition: item.position }} /></div><div className="featured-menu-copy"><span>{String(index + 1).padStart(2,"0")}</span><h3>{item.name}</h3></div></article>)}</div><div className="featured-menu-heading beverage-heading"><p className="eyebrow">Signature Beverages</p><h3>Six refreshing signatures, styled to stand out.</h3></div><div className="beverage-menu-grid">{beverageMenu.map((item, index) => <article className="featured-menu-card beverage-menu-card" key={item.name}><div className="featured-menu-photo beverage-menu-photo"><Image src={item.image} alt={`${item.name}, a Juang Cafe signature beverage`} fill sizes="(max-width: 600px) 100vw, (max-width: 900px) 50vw, 33vw" /></div><div className="featured-menu-copy beverage-menu-copy"><span>{String(index + 1).padStart(2,"0")}</span><h3>{item.name}</h3><p>{item.description}</p></div></article>)}</div><div className="three-grid menu-groups">{menuGroups.map((group) => <article className="menu-card" key={group.title}><h3>{group.title}</h3><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>
    <section id="inclusive-employment" className="section inclusion"><div className="container"><div className="split inclusion-copy"><div><HandHeart size={44} aria-hidden /><SectionHeading eyebrow="06 · Inclusive Employment" title="Equal Opportunity, Meaningful Work." light /></div><div><p className="lead">Inclusive employment is central to Juang Cafe’s identity. The brand is committed to creating structured, supportive, and meaningful roles for people with Down syndrome based on each person’s abilities, strengths, readiness, and development needs.</p><p>Potential roles may include greeting, light table service, preparation, packaging, cleaning support, and selected operational tasks. Implementation should involve clear SOPs, training, safe supervision, fair treatment, and coordination with families, communities, foundations, or professional companions.</p><p className="policy-note">Inclusion is an operating commitment—not a marketing gimmick.</p></div></div><figure className="inclusion-illustration"><Image src="/images/juang-cafe/inclusive-employment.webp" alt="Adults with Down syndrome working professionally as Juang Cafe team members, preparing coffee and serving guests" fill sizes="(max-width: 900px) 100vw, 1180px" /><figcaption><strong>Ability in action.</strong><span>Structured support, meaningful roles, dignity, and room to grow.</span></figcaption></figure></div></section>
    <section id="target-market" className="section"><div className="container"><SectionHeading eyebrow="07 · Target Market" title="Three communities, one welcoming space." /><figure className="target-illustration"><Image src="/images/juang-cafe/target-communities.webp" alt="University students, young professionals, and a creative community sharing one welcoming Juang Cafe space" fill sizes="(max-width: 900px) 100vw, 1180px" /><figcaption><strong>Different needs. Shared belonging.</strong><span>Students · Professionals · Communities</span></figcaption></figure><div className="three-grid">{targetMarkets.map((group) => <article className="audience-card" key={group.title}><Users aria-hidden /><h3>{group.title}</h3><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>
    <section className="section surface-white"><div className="container"><SectionHeading eyebrow="08 · Business Model" title="Built around daily trade, designed for optionality." /><div className="revenue-grid"><article><p className="eyebrow">Core Revenue</p><h3>Food, coffee, beverages, ice cream, and desserts.</h3></article><article><p className="eyebrow">Future Opportunities</p><h3>Meeting packages, reservations, catering, private events, merchandise, packaged products, and potential partnerships.</h3></article></div></div></section>
    <section id="connected-operations" className="section surface-ceramic"><div className="container"><SectionHeading eyebrow="09 · Connected Operations" title="From Table to Dashboard, Every Step Connected." body="Juang Cafe plans to use an integrated digital workflow that connects table ordering, cashier records, kitchen preparation, inventory movement, and management reporting in one traceable system." /><figure className="technology-illustration"><Image src="/images/juang-cafe/connected-operations.webp" alt="Integrated Juang Cafe technology connecting QR table ordering, cashier, kitchen, inventory, and an investor dashboard" fill sizes="(max-width: 900px) 100vw, 1180px" /><figcaption><strong>One order. One connected flow.</strong><span>QR Order · Cashier · Kitchen · Inventory · Dashboard</span></figcaption></figure><div className="technology-grid">{[
      [QrCode, "Simpler Ordering", "Guests scan a QR code at the table and send orders directly, helping reduce queues and unnecessary waiting."],
      [ReceiptText, "More Accurate Execution", "A shared order record across cashier and kitchen helps minimize repeated entry and avoid preventable order mistakes."],
      [PackageCheck, "Traceable Inventory", "Ingredient usage, stock changes, and asset movement can be recorded against daily operating activity."],
      [View, "Clearer Investor Visibility", "Authorized reporting gives investors a clearer view of sales, stock, and asset movement without disrupting operations."],
    ].map(([Icon,title,text]) => { const TechnologyIcon = Icon as typeof QrCode; return <article className="technology-card" key={title as string}><TechnologyIcon aria-hidden /><div><h3>{title as string}</h3><p>{text as string}</p></div></article>; })}</div><p className="technology-note">The final technology stack, access controls, integrations, and reporting scope will be validated during implementation.</p></div></section>
    <section id="marketing-strategy" className="section dark-band"><div className="container"><SectionHeading eyebrow="10 · Go-to-Market" title="Community before campaign." light /><figure className="marketing-illustration"><Image src="/images/juang-cafe/marketing-ecosystem.webp" alt="Juang Cafe marketing ecosystem connecting digital storytelling, campus activation, community events, and strategic partnership conversations" fill sizes="(max-width: 900px) 100vw, 1180px" /><figcaption><strong>Build relationships before reach.</strong><span>Digital · Campus · Community · Partnership</span></figcaption></figure><div className="four-grid">{[
      ["Digital", "Instagram, TikTok, Google Business Profile, creators, UGC, founder storytelling"],
      ["Campus", "Potential ambassadors, study packages, student offers, partnerships, sponsorship"],
      ["Community", "Cultural nights, open mic, workshops, inclusive programs, exhibitions"],
      ["Partnership", "Proposed collaboration with universities, companies, foundations, communities, and cultural organizations"],
    ].map(([title,text]) => <article className="dark-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section"><div className="container split"><SectionHeading eyebrow="11 · Competitive Advantage" title="Why Juang Cafe Can Stand Out." /><div className="advantage-list">{advantages.map((item) => <div key={item}><Lightbulb aria-hidden /><span>{item}</span></div>)}</div></div></section>
    <section className="section surface-ceramic"><div className="container"><SectionHeading eyebrow="12 · Future Impact Measurement" title="Measure progress, never manufacture it." body="These are proposed indicators for the future—not current results." /><div className="impact-list">{["Inclusive employees trained and hired","Training hours and development progress","Community partnerships and events","Employee retention","Customer awareness of inclusive employment"].map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section id="roadmap" className="section surface-white"><div className="container"><SectionHeading eyebrow="13 · Roadmap" title="A disciplined path from validation to growth." /><div className="timeline">{roadmap.map((step, index) => { const PhaseIcon = roadmapIcons[index]; return <article key={step.phase}><div className="phase-illustration"><PhaseIcon aria-hidden /><span>{String(index + 1).padStart(2, "0")}</span></div><div className="phase-copy"><span>{step.phase}</span><h3>{step.title}</h3><p>{step.items}</p></div></article>; })}</div></div></section>
    <section id="investment" className="section investment"><div className="container"><div className="split"><SectionHeading eyebrow="14 · Investment Opportunity" title="Expanding a Sustainable and Inclusive Brand Together." light /><div><p className="lead">Juang Cafe welcomes aligned investors and strategic partners to support responsible expansion across Indonesia. Potential use of funds includes new locations, renovation, equipment, furniture, inventory, licensing, recruitment, inclusive training, technology, marketing, and working capital.</p><ButtonLink href="/contact" variant="light">Discuss the Investment</ButtonLink></div></div><div className="investment-grid">{["Funding Requirement","Proposed Business Structure","Revenue Projection","Break-Even Projection","Opening Target","Investor Return Structure"].map((item) => <article key={item}><span>{item}</span><strong>To Be Finalized</strong></article>)}</div></div></section>
    <section className="section closing"><div className="container closing-inner"><div><p className="eyebrow">Let’s build together</p><h2>Let’s Build a Cafe Where Everyone Has a Place.</h2></div><div className="actions"><ButtonLink href="/contact" variant="light">Connect With Juang Group</ButtonLink><ButtonLink href="/" variant="light-outline">Return to Juang Group</ButtonLink></div></div></section>
  </>;
}
